module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:'Admin',
    CART_COLLECTION:'cart',
    WISHLIST_COLLECTION:'wishlist',
    ORDER_COLLECTION:'order',
    COUPON_COLLECTION:'coupons'
}